---
name: Build Workflow

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: Upload test
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: test.txt