name: 🦅 Release Builds
on:
  workflow_call:

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: 📛 Rename release
        uses: actions/github-script@v6
        with:
          result-encoding: json
          script: |
            const { repo, owner } = context.repo;
            const date = new Date();
            const year = date.getFullYear().toString();
            const month = (date.getMonth() + 1).toString();
            const day = (date.getDay() + 1).toString();
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: context.payload.release.id,
              name: 'test-' + context.payload.release.name + '-' + year + month + day,
            });

  release:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        name: [test]
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

      - name: LS
        run: ls -R
        shell: bash

      - name: 📦 Pack build as zip
        run: zip -r ${{ matrix.name }}.zip ${{ matrix.name }}
        shell: bash

      - name: ⏫ Upload Release Asset
        uses: actions/github-script@v6
        with:
          result-encoding: json
          script: |
            const FS = require('node:fs')
            const { repo, owner } = context.repo;
            return await github.rest.repos.uploadReleaseAsset({
              owner,
              repo,
              release_id: context.payload.release.id,
              name: '${{ matrix.name }}.zip',
              data: FS.readFileSync('${{ github.workspace }}/${{ matrix.name }}.zip')
            });
