name: 🦅 Release Builds
on:
  workflow_call:

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        name: [test]
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: Download android-template
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

      - name: ⏫ Upload Release Asset
        id: upload-release-asset
        uses: actions/github-script@v6
        with:
          result-encoding: json
          script: |
            const FS = require('node:fs')
            const { repo, owner } = context.repo;
            return await github.rest.repos.uploadReleaseAsset({
              owner,
              repo,
              release_id: context.payload.release.id,
              name: '${{ matrix.name }}',
              data: FS.readFileSync('${{ github.workspace }}/${{ matrix.name }}')
            });
