name: Run

on:
  release:
    types: [published]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:

  build:
    uses: ./.github/workflows/build.yml

  release:
    name: 🦅 Release
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [build]
    uses: ./.github/workflows/release_builds.yml
    secrets: inherit
